name: BookInfo CI/CD with Istio

on:
  push:
    branches:
      - main

jobs:
  MiniKube_Setup:
    name: Setup Minikube & clean up
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi
          kubectl version --client

      - name: Start Minikube
        run: |
          if ! minikube status; then
            echo "Starting Minikube..."
            minikube start
          else
            echo "Minikube is already running."
            kubectl delete all --all --namespace=default
            kubectl delete all --all -n istio-system
          fi

      - name: Set Minikube IP
        id: set-ip
        run: |
          MINIKUBE_IP=$(minikube ip)
          echo "MINIKUBE_IP=$MINIKUBE_IP" >> $GITHUB_ENV
          echo "Minikube IP set to $MINIKUBE_IP"

  istioctl_install:
    runs-on: self-hosted
    needs: [MiniKube_Setup]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl (if not already present)
        run: |
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi
          kubectl version --client

      - name: Check and Install Istio
        run: |
          # Download and extract Istio if not already present
          if [ ! -d "$HOME/istio-1.25.0" ]; then
            echo "Istio not found. Downloading and installing Istio 1.25.0..."
            curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.25.0 sh -
          else
            echo "Istio directory already exists."
          fi

          # Set PATH to include istioctl binary
          export PATH=$HOME/istio-1.25.0/bin:$PATH
          echo "PATH updated: $PATH"

          # Verify istioctl is available
          if ! command -v istioctl &> /dev/null; then
            echo "ERROR: istioctl not found after setting PATH. Exiting..."
            exit 1
          fi

          # Check if Istio is installed in the cluster
          if istioctl x precheck; then
            echo "Istio is already installed in the cluster."
          else
            echo "Installing Istio into Minikube cluster..."
            istioctl install --set profile=demo -y
            kubectl label namespace default istio-injection=enabled --overwrite
            echo "Istio installed successfully."
            istioctl x precheck
          fi

          # Output Minikube IP for reference
          echo "Minikube IP: $MINIKUBE_IP"
          echo "Check the application at: http://$MINIKUBE_IP/productpage (after deploying BookInfo)"
