name: BookInfo CI/CD with Istio

on:
  push:
    branches:
      - main

jobs:
  MiniKube_Setup:
    name: Setup Minikube & clean up
    runs-on: self-hosted
    outputs:
      minikube_ip: ${{ steps.set-ip.outputs.minikube_ip }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi
          kubectl version --client

      - name: Start Minikube
        run: |
          if ! minikube status; then
            echo "Starting Minikube..."
            minikube start
          else
            echo "Minikube is already running."
            kubectl delete all --all --namespace=default
            kubectl delete all --all -n istio-system
          fi

      - name: Set Minikube IP
        id: set-ip
        run: |
          MINIKUBE_IP=$(minikube ip)
          if [ -z "$MINIKUBE_IP" ]; then
            echo "ERROR: Failed to get Minikube IP"
            minikube status
            exit 1
          fi
          echo "MINIKUBE_IP=$MINIKUBE_IP" >> $GITHUB_ENV
          echo "minikube_ip=$MINIKUBE_IP" >> $GITHUB_OUTPUT
          echo "Minikube IP set to $MINIKUBE_IP"

  istioctl_install:
    runs-on: self-hosted
    needs: [MiniKube_Setup]
    env:
      MINIKUBE_IP: ${{ needs.MiniKube_Setup.outputs.minikube_ip }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install kubectl (if not already present)
        run: |
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi
          kubectl version --client

      - name: Check and Install Istio
        run: |
          if [ ! -d "$HOME/istio-1.25.0" ]; then
            echo "Istio not found. Downloading and installing Istio 1.25.0 to $HOME..."
            curl -LO https://github.com/istio/istio/releases/download/1.25.0/istio-1.25.0-linux-amd64.tar.gz
            tar -xzf istio-1.25.0-linux-amd64.tar.gz -C $HOME
            rm istio-1.25.0-linux-amd64.tar.gz
          else
            echo "Istio directory already exists at $HOME/istio-1.25.0"
          fi

          export PATH="$HOME/istio-1.25.0/bin:$PATH"
          echo "PATH updated: $PATH"
          ls -l "$HOME/istio-1.25.0/bin/istioctl" || echo "istioctl not found in $HOME/istio-1.25.0/bin"
          if ! command -v istioctl &> /dev/null; then
            echo "ERROR: istioctl not found after setting PATH. Exiting..."
            exit 1
          fi

          # Check if Istio is installed by looking for the istio-system namespace
          if kubectl get namespace istio-system &> /dev/null; then
            echo "Istio is already installed in the cluster."
            kubectl get pods -n istio-system
          else
            echo "Istio not found in cluster. Installing Istio into Minikube..."
            istioctl install --set profile=demo -y
            kubectl label namespace default istio-injection=enabled --overwrite
            echo "Istio installed successfully."
            istioctl x precheck
            kubectl get pods -n istio-system
          fi

          echo "Minikube IP: $MINIKUBE_IP"
          echo "Check the application at: http://$MINIKUBE_IP/productpage (after deploying BookInfo)"
