name: Test Runner
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print Debug Info
        run: |
          echo "Hello Team from $(whoami) on $(hostname)"
          date
          echo "PATH: $PATH"
